### PR TITLE
Add ES username and password env variables to index cleaner cronjob

### PR DESCRIPTION
**Pull request by venukasu**

### CODE REVIEW

**Comment by naseemkullah** [comment]
Thanks @venukasu! Could you please gpg sign the commit? This repo currently has this requirement.

**Comment by naseemkullah** [comment]
Hi @venukasu , `ES_USERNAME` and `ES_PASSWORD` will now be passed 


ES related configurable variables defined once (Though not all configurable variable names are consistent with es-index-cleaner, fortunately `ES_USERNAME` & `ES_PASSWORD` are): https://github.com/jaegertracing/helm-charts/blob/fc87249b7f3b8a0a6e5fd891d7a7a52ef6e17cd4/charts/jaeger/templates/_helpers.tpl#L293-L316

Passed to the es-index-cleaner and all components that talk to ES as so: https://github.com/jaegertracing/helm-charts/blob/fc87249b7f3b8a0a6e5fd891d7a7a52ef6e17cd4/charts/jaeger/templates/es-index-cleaner-cronjob.yaml#L47

Please let me know if that works!

cc @pavolloffay an example of added value from consistent config opts.

**Comment by venukasu** [comment]
It looks cleaner now. Thank you for the changes.

**Comment by naseemkullah** [comment]
My pleasure @venukasu

**Pull request closed without merging**
