### PR TITLE
Adds hpa permissions to jaeger-operator role/cluster role

### LINKED ISSUE #84: HorizontalPodAutoscalers permissions missing in RBAC.
I installed jaeger-operator chart version 2.14.0  with default values and get some problems (I'll link issue with actual problems later).

Operator pod's logs linked bellow:
```
time="2020-03-25T19:06:36Z" level=info msg=Versions arch=amd64 identity=jaeger.jaeger-operator jaeger=1.17.0 jaeger-operator=v1.17.0 operator-sdk=v0.15.1 os=linux version=go1.13.3
time="2020-03-25T19:06:37Z" level=info msg="Consider running the operator in a cluster-wide scope for extra features"
time="2020-03-25T19:06:38Z" level=info msg="Auto-detected the platform" platform=kubernetes
time="2020-03-25T19:06:38Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=no
time="2020-03-25T19:06:38Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no
time="2020-03-25T19:06:38Z" level=info msg="The service account running this operator does not have the role 'system:auth-delegator', consider granting it for additional capabilities"
time="2020-03-25T19:06:40Z" level=warning msg="could not create ServiceMonitor object" error="servicemonitors.monitoring.coreos.com \"jaeger-operator-metrics\" already exists"
time="2020-03-25T19:06:40Z" level=info msg="Storage type not provided. Falling back to 'memory'" instance=jaeger namespace=jaeger
E0325 19:06:41.586604       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:42.588331       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:43.590036       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:44.591980       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:45.593800       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:46.595867       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:47.597640       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:48.599713       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:49.601643       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:50.603865       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:51.605800       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:52.607910       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:53.610830       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:54.612751       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:55.614784       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:56.617051       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:57.619046       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:58.620690       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:06:59.622586       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:00.624336       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:01.626495       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:02.628659       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:03.630611       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:04.632452       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:05.634346       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:06.636630       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:07.638557       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:08.640510       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:09.642505       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:10.644541       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:11.646544       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:12.648399       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:13.650053       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:14.651872       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:15.654041       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:16.656221       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:17.658187       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:18.660068       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:19.661891       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:20.663733       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:21.665194       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:22.667020       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:23.668687       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:24.670580       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:25.672594       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:26.674489       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:27.676433       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:28.678256       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:29.680386       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:30.682303       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:31.684550       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:32.686414       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:33.688449       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:34.690358       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:35.692292       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:36.694149       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:37.700222       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:38.702125       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:39.703855       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:40.706536       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:41.708612       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:42.710402       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:43.712252       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:44.714268       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:45.716290       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
E0325 19:07:46.718484       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v2beta2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "jaeger"
```

So chart rbac is missing horizontalpodautoscalers permissions in RBAC template

### PR DESCRIPTION
**Pull request by dm3ch**
Adds hpa permissions to jaeger-operator role/cluster role
fixes #84

### CODE REVIEW

**Comment by naseemkullah** [comment]
Thanks @dm3ch 
But I believe this is a duplicate of https://github.com/jaegertracing/helm-charts/pull/78.

cc @cpanato @batazor Please review either/both of these PRs, thanks!

**Comment by dm3ch** [comment]
> Thanks @dm3ch
> But I believe this is a duplicate of #78.
> 
> cc @cpanato @batazor Please review either/both of these PRs, thanks!

Yep, it seems so.

**Comment by elkh510** [comment]
hi
any updates?

**Comment by batazor** [comment]
Merged in #78

**Pull request closed without merging**
