### PR TITLE
Fixed: typo in README

### PR DESCRIPTION
**Pull request by Jasstkn**
Signed-off-by: Jasstkn <jasssstkn@yahoo.com>

Open new PR due to problems with rebasing and sign off previous commits.

### CODE REVIEW

**Comment by naseemkullah** [comment]
Thanks @Jasstkn !

This one is missing the GPG signature.

i **think** you can `git commit --amend -S` but please double check.

Alternatively you can set gpg signature by default as per https://help.github.com/en/github/authenticating-to-github/signing-commits

**Comment by naseemkullah** [comment]
Hi @Jasstkn I just realized why the README is as such, not all components take command line parameters, namely the cassandra schema job and the elastic search cleaner do not.

**Comment by Jasstkn** [comment]
@naseemkullah ok, can I fix the typo anyway? to something like <agent|collector...>?

Screenshot 2020-03-29 at 16 35 33

**Comment by naseemkullah** [comment]
> @naseemkullah ok, can I fix the typo anyway? to something like <agent|collector...>?
> 
> Screenshot 2020-03-29 at 16 35 33

oh yeah 💯 ! Did not realize that it rendered so badly, thanks.

**Comment by Jasstkn** [comment]
@naseemkullah fixed.

**Comment by naseemkullah** [comment]
Thanks @Jasstkn, please just GPG sign the commit and we are good to go.

Build is broken because https://github.com/helm/charts/pull/21659 so we can ignore that.

**Comment by Jasstkn** [comment]
@naseemkullah done. OpenSource is tough :)

**Comment by naseemkullah** [comment]
> @naseemkullah done. OpenSource is tough :)

Agreed! But worth it :) Thanks!

**Pull request merged**
