### PR TITLE
[jaeger] Added missing affinity section for Ingester deployment

### PR DESCRIPTION
**Pull request by sgolod**
#### Checklist

- [X] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)

### CODE REVIEW

**Comment by mehta-ankit** [comment]
@sgolod can you rebase and resolve conflicts please.

**Comment by sgolod** [comment]
> @sgolod can you rebase and resolve conflicts please.

done

**Comment by mehta-ankit** [comment]
@sgolod can you squash all the commits into 1 please.

**Comment by sgolod** [comment]
> @sgolod can you please squash all the commits into 1 please. 🙏🏽

I'm ashamed to say 🤦‍♂️, but I don't know how to do it. I'll open a new PR with a single commit and close this one.

**Pull request closed without merging**
