### PR TITLE
[Jaeger] add podAnnotations to spark cronjob

### LINKED ISSUE #222: [Spark cronjob] Add jobAnnotations to Template
Hi,

Could you add `jobAnnotations` to spark template? When jobs are used with istio or with vault-webhook it is needed to add some annotations. And the annotations in this case are only for the cronjob, not for the job.

Thanks :)

### PR DESCRIPTION
**Pull request by ichasco-heytrade**
#### What this PR does

Add podAnnotations in spark cronjob

#### Which issue this PR fixes

- fixes #222

### CODE REVIEW

**Comment by naseemkullah** [comment]
Please bump chart version

**Comment by ichasco-heytrade** [comment]
> Please bump chart version

Done

**Comment by naseemkullah** [comment]
Please sign commits seems like DCO check not passing

**Comment by ichasco-heytrade** [comment]
Done :)

**Review by naseemkullah — APPROVED** [review]

**Comment by naseemkullah** [comment]
Thanks!

**Pull request merged**
