### PR TITLE
[jaeger] Add secret volume for cassandra tls

### PR DESCRIPTION
**Pull request by kwangil-ha**
Signed-off-by: 하광일/TC_Core Engineering <kwangil_ha@yanolja.com>

### CODE REVIEW

**Comment by naseemkullah** [comment]
solves #15 

Thanks @kwangil-ha! Just missing the chart version bump and we should be good to go!

**Comment by arpitjindal97** [comment]
LGTM

**Comment by naseemkullah** [comment]
@kwangil-ha re: chart version bump, that would be here: https://github.com/jaegertracing/helm-charts/blob/31ae789193420cbb3d4a2bb34f994ba52d4da889/charts/jaeger/Chart.yaml#L5 🙏

**Comment by sshah90** [comment]
Hi, @yurishkuro any specific reason to close this PR?

**Comment by yurishkuro** [comment]
I don't remember closing it. It may have happened after renaming master->main branch. I can't reopen it either, it says source repo was deleted.

**Comment by sshah90** [comment]
Thanks for confirming it @yurishkuro 

I will open new PR with these fixes as #15  is kind of blocking us.

**Pull request closed without merging**
