### PR TITLE
[jaeger] secret volume for cassandra tls

### LINKED ISSUE #15: [jaeger] Cassandra TLS broken
Please skip to https://github.com/jaegertracing/helm-charts/issues/15#issuecomment-589994120

Original issue has taken a different road.

### PR DESCRIPTION
**Pull request by sshah90**
Signed-off-by: sshah90 <shahsmit25193@gmail.com>

#### What this PR does

Add Volume block if Cassandra tls enable

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format,
will close that issue when PR gets merged)*

- fixes #15

#### Checklist

- [x] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)

### CODE REVIEW

**Review by naseemkullah — APPROVED** [review]
Thanks!

**Comment by naseemkullah** [comment]
> The base branch requires all commits to be signed.
https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification

**Comment by sshah90** [comment]
> > The base branch requires all commits to be signed.
> > https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification

Working on it. Thanks

**Comment by sshah90** [comment]
@naseemkullah  trying to amend previous commits using `git commit --amend -s -c`  but no luck yet.

Any tip/code snippet would be useful.

Thanks

**Comment by naseemkullah** [comment]
@sshah90 

Try `git rebase -i ae0638771f903dc68da5503c26cdca30dde38d54` and then squash it all, or edit the unsigned commits (the two first)

**Comment by sshah90** [comment]
Opening another PR with proper commits signatures.

I apologize for the little mess up here. Thanks for your help @naseemkullah

**Pull request closed without merging**
