### PR TITLE
[jaeger] Update Jaeger version in helm chart

### PR DESCRIPTION
**Pull request by tronda**
#### What this PR does
Update to the latest released Jaeger version.
#### Which issue this PR fixes
None

#### Checklist

- [x] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [x] README.md has been updated to match version/contain new values

### CODE REVIEW

**Comment by tronda** [comment]
Not sure why the Kafka related template fails for this change.

**Comment by tronda** [comment]
> Maybe we can leave the Kafka sub-chart version untouched for now 🤔

I've pinned the Kafka chart on the previous version with the latest commit.

**Comment by bens545** [comment]
It's likely still failing due to the common chart update.  Try reverting it to the previous version and testing.

**Comment by alex1989hu** [comment]
@tronda is there any particular reason (probably I overlooked it) why `appVersion` change is not enough here?

On the other hand, `role.yaml` must be also updated due to 

- https://github.com/jaegertracing/jaeger-operator/pull/2409
- https://github.com/jaegertracing/jaeger-operator/pull/2466

**Comment by tronda** [comment]
> @tronda is there any particular reason (probably I overlooked it) why `appVersion` change is not enough here?
I just wanted the latest version of Jaeger by default with the helm chart and my own preference to always update to the latest dependencies. 

> On the other hand, `role.yaml` must be also updated due to
> 
> * [Use the host set in the Ingess field for the OpenShift Route jaeger-operator#2409](https://github.com/jaegertracing/jaeger-operator/pull/2409)
> * [fixes #1568 #2225 jaeger-operator#2466](https://github.com/jaegertracing/jaeger-operator/pull/2466)
Probably somebody else should do the update since I don't know the details here.

**Pull request closed without merging**
