### PR TITLE
Allow to use external es host

### PR DESCRIPTION
**Pull request by cgroschupp**
After #45 it is no longer possible to set an external elasticsearch host.

### CODE REVIEW

**Comment by naseemkullah** [comment]
@arpitjindal97 You recently made this change and @cgroschupp would like to change it back

Could you both please explain how this helper is affecting the es host name?

**Comment by arpitjindal97** [comment]
Hi everyone, please give me some hours.

I'm currently in an event in SAP. I don't know how it is breaking. Just give me some hours. Let me check it once.

**Comment by cgroschupp** [comment]
my values:
```
storage:
  type: elasticsearch
  elasticsearch:
    host: myhost
    scheme: https
provisionDataStore:
  elasticsearch: false
```
The if block of the helper returns no value if provisionDataStore.elasticsearch is set to false.
But this is necessary when the es not managed by the chart.

**Comment by naseemkullah** [comment]
I see

Would it make sense to simply have

`{{- printf "%s://%s:%s" .Values.storage.elasticsearch.scheme .Values.storage.elasticsearch.host $port }}`

regardless of provisioned or not? Please both let me know if that solves use cases of provisioned and external ES.

**Comment by arpitjindal97** [comment]
#49 fixed everything

**Comment by cgroschupp** [comment]
we have three cases:
* provisionDataStore=false
* provisionDataStore=true
* provisionDataStore=true and nameOverride

I do not know, but I think this is easier to understand:
```
{{- define "elasticsearch.client.url" -}}
{{- $port := .Values.storage.elasticsearch.port | toString -}}
{{- $host := .Values.storage.elasticsearch.host -}}
{{- if .Values.provisionDataStore.elasticsearch }}
{{- $host := printf "%s-%s-%s" .Release.Name "elasticsearch" "client" | trunc 63 | trimSuffix "-" -}}
{{- if .Values.storage.elasticsearch.nameOverride }}
{{- $host := printf "%s" .Values.storage.elasticsearch.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end }}
{{- printf "%s://%s:%s" .Values.storage.elasticsearch.scheme $host $port }}
{{- end -}}
```

**Comment by cgroschupp** [comment]
> #49 fixed everything

see: https://github.com/jaegertracing/helm-charts/pull/49#issuecomment-586320169

**Comment by cgroschupp** [comment]
> I see
> 
> Would it make sense to simply have
> 
> `{{- printf "%s://%s:%s" .Values.storage.elasticsearch.scheme .Values.storage.elasticsearch.host $port }}`
> 
> regardless of provisioned or not? Please both let me know if that solves use cases of provisioned and external ES.

@naseemkullah You're right, I changed it.

**Comment by naseemkullah** [comment]
lgtm @arpitjindal97  does this work for you?

Makes me think we should just introduce storage.elasticsearch.url in a non-breaking mannger... but that could be a separate PR

**Comment by arpitjindal97** [comment]
Yes, It looks good to me. I think it will work for all scenarios. We can merge it.

**Pull request merged**
