### PR TITLE
[jaeger] Add ability to manually set nodeport for jaeger-collector

### PR DESCRIPTION
**Pull request by maximsnezhkov**
Hello.
My installation has some services landed outside the k8s cluster. Manually set a nodePort number for collector is important to bring agent's config valid over time.

### CODE REVIEW

**Comment by naseemkullah** [comment]
Thanks @maximsnezhkov !

**Comment by naseemkullah** [comment]
Hi @maximsnezhkov , could you please GPG sign your commits?

**Comment by maximsnezhkov** [comment]
@naseemkullah sorry it is my first time using signed commits) I've done it with squash.

**Comment by naseemkullah** [comment]
No problem at all and thank you again for this PR @maximsnezhkov!

**Comment by naseemkullah** [comment]
Seems like CI is experiencing: https://github.com/actions/checkout/issues/23
Could you please try:
```
git commit --allow-empty -m "rerun build"
```
?
Might help. 🤷‍♂

**Comment by maximsnezhkov** [comment]
@naseemkullah I've done it.

**Pull request merged**
