### PR TITLE
[jaeger-operator] Update version jaeger-operator to v1.24.0

### LINKED ISSUE #266: [jaeger-operator] Update jaeger-operator to 1.23.0
The new jaeger-operator version should be used as default.

### PR DESCRIPTION
**Pull request by batazor**
#### What this PR does

Update version jaeger-operator to v1.24.0

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format,
will close that issue when PR gets merged)*

- fixes #266

#### Checklist

- [x] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
thanks for doing this!

**Comment by stevehipwell** [comment]
@batazor I can't find any documentation on the operator or Jaeger project as to why the min K8s version has changed to v1.19, could you expand on this?

**Comment by batazor** [comment]
> @batazor I can't find any documentation on the operator or Jaeger project as to why the min K8s version has changed to v1.19, could you expand on this?

I looked at the [Compatibility matrix](https://github.com/jaegertracing/jaeger-operator#compatibility-matrix)

**Comment by stevehipwell** [comment]
Thanks @batazor I was looking for changes on the release notes and completely missed the compatibility matrix.

**Pull request merged**
