### PR TITLE
[jaeger] feat: add option to add "envFrom" in deployments

### PR DESCRIPTION
**Pull request by sedflix**
#### What this PR does

This PR adds an option of giving "envFrom" to the deployment manifest. 

#### Checklist

- [x] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [x] README.md has been updated to match version/contain new values (> not sure where to update new version in the readme)

### CODE REVIEW

**Review by naseemkullah — APPROVED** [review]

**Review by mehta-ankit — APPROVED** [review]

**Comment by mehta-ankit** [comment]
@sedflix the commit needs to be signed. Can you do that please.

**Comment by mehta-ankit** [comment]
@sedflix can you resolve the conflicts and GPG sign the commit please.

**Comment by pavelnikolov** [comment]
@sedflix ping

**Comment by pavelnikolov** [comment]
@sedflix 
> **Merging is blocked**
> The base branch requires all commits to be signed

**Review by pavelnikolov — CHANGES_REQUESTED** [review]
Please, sign your commit.

**Review by pavelnikolov — APPROVED** [review]

**Comment by pavelnikolov** [comment]
I don't understand why this keeps failing.
Screenshot 2023-05-23 at 11 15 39
I read the docs and it seems that [it falls in this case](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#signature-verification-for-rebase-and-merge). Could you, please, try to rebase locally and force push with a signed commit. Hopefully, that will resolve the problem.

**Pull request closed without merging**
