### PR TITLE
use "enabled" key to add zipkin port to collector

### PR DESCRIPTION
**Pull request by golgoth31**
use "enabled" key to add zipkin port to collector (avoid warning from helm)

Currently, only the key "zipkin" is used and helm complains about it:
2020/03/06 09:55:11 Warning: Merging destination map for chart 'jaeger'. The destination item 'zipkin' is a table and ignoring the source 'zipkin' as it has a non-table value of: <nil>
2020/03/06 09:55:11 Warning: Merging destination map for chart 'jaeger'. The destination item 'zipkin' is a table and ignoring the source 'zipkin' as it has a non-table value of: <nil>

Signed-off-by: David Sabatie <david.sabatie@delair.aero>

### CODE REVIEW

**Comment by golgoth31** [comment]
Hi,
Is there any way to make the lint-test ok ?
thanks

**Comment by naseemkullah** [comment]
Hi @golgoth31 thanks for bringing this up.
A nitpick: could we try adding empty braces as follows? I prefer this to having only one of the ports with an `enabled` value but can resort to that if below does not work.

```
    zipkin: {}
      # port: 9411
```

**Comment by golgoth31** [comment]
No problem, I make the test

**Comment by golgoth31** [comment]
Done, it's working as expected, without warnings. Thank you

**Comment by naseemkullah** [comment]
Thanks @golgoth31!

**Pull request merged**
