### PR TITLE
[jaeger] Add missing loadBalancerIp to collector-svc template.

### PR DESCRIPTION
**Pull request by indreek**
#### What this PR does
Adds missing loadbalancer ip to service

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format,
will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [x] README.md has been updated to match version/contain new values

### CODE REVIEW

**Comment by pavelnikolov** [comment]
@indreek could you, please, DCO sign your commits?

**Review by pavelnikolov — APPROVED** [review]

**Comment by pavelnikolov** [comment]
@indreek could you, please, [DCO sign](https://github.com/jaegertracing/helm-charts/pull/467/checks?check_run_id=13685680888)? Alternatively, let me know if you don't plan to do that.

**Comment by indreek** [comment]
@pavelnikolov Hey. Will this commit work now?

**Comment by pavelnikolov** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
