### PR TITLE
[jaeger] incubator repo url changed

### PR DESCRIPTION
**Pull request by survivant**
to avoid the error
````
helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
Error: repo "https://kubernetes-charts-incubator.storage.googleapis.com/" is no longer available; try "https://charts.helm.sh/incubator" instead
````

### CODE REVIEW

**Review by naseemkullah — APPROVED** [review]
Thanks! Could you please bump the chart version?

**Comment by survivant** [comment]
Even if it's just the readme?

**Comment by naseemkullah** [comment]
> Even if it's just the readme?

Yep! CI is setup to cut a release upon every merge, even just for README changes.

Also, DCO will need to be signed to merge this.

**Comment by survivant** [comment]
I'll do the DCO later, I can't do it from here and the option is not available from github webpage :(

**Comment by naseemkullah** [comment]
> I'll do the DCO later, I can't do it from here and the option is not available from github webpage :(

Ok sounds good, thanks!

**Comment by survivant** [comment]
ready to review

**Review by naseemkullah — APPROVED** [review]

**Comment by pavelnikolov** [comment]
@survivant you must sign your commit(s)

**Comment by pavelnikolov** [comment]
@survivant I had to bump the version again, however, unfortunately there are still some commits that are unverified. Could you, please, delete/squash them so that you leave only one verified commit? Otherwise, I am not able to merge this PR. 
Alternatively, I can close this PR and push a new one with one one PR.

**Review by cpanato — APPROVED** [review]

**Comment by cpanato** [comment]
@survivant you need to sign your commit, thank

**Comment by survivant** [comment]
I'll create a new PR from scratch with only one commit signed.  it will be easier that way.

**Pull request closed without merging**
