### PR TITLE
[jaeger] Provide the ability to connect to Elasticsearch with TLS

### PR DESCRIPTION
**Pull request by OpenGuidou**
Signed-off-by: Guillaume DOUSSIN <guillaume.doussin@amadeus.com>

#### What this PR does
Provide the ability to connect to an elastic search cluster using TLS.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format,
will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [x] README.md has been updated to match version/contain new values

### CODE REVIEW

**Comment by pavelnikolov** [comment]
@OpenGuidou you have unsigned commits

**Comment by OpenGuidou** [comment]
> @OpenGuidou you have unsigned commits

Is it better now ?
I can see it in the commit tab:
image

**Comment by OpenGuidou** [comment]
@pavelnikolov Is it ok now ? Can we merge this change ?

**Comment by pavelnikolov** [comment]
I still can't merge it. Is your commit GPG signed?

**Comment by OpenGuidou** [comment]
@pavelnikolov it should be ok now, there was a small glitch on my side

**Comment by pavelnikolov** [comment]
Could you, please, resolve the conflicts and I'd be happy to merge this.

**Comment by OpenGuidou** [comment]
Done !

**Comment by mehta-ankit** [comment]
@OpenGuidou Can you please gpg sign the commit as well 🙏🏼

**Pull request merged**
