### PR TITLE
Added Elasticsearch indexPrefix option

### PR DESCRIPTION
**Pull request by arpitjindal97**
Similar to keyspace in cassandra

### CODE REVIEW

**Comment by naseemkullah** [comment]
Thanks @arpitjindal97!

I think it would be best to wrap these around if statements in the templates, and by default not set any aka comment out the `indexPrefix` line in values.yaml (or set its' value `null`? I forget if that works).

**Comment by naseemkullah** [comment]
Oh and please add the value in README for this optional prefix of Jaeger indices. 🙏

**Comment by arpitjindal97** [comment]
hahaha, Sure

**Comment by naseemkullah** [comment]
👍

**Pull request merged**
