### PR TITLE
[jaeger] Added toleration to cassandra-schema-job.yaml

### PR DESCRIPTION
**Pull request by araamini**
#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format,
will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [x] README.md has been updated to match version/contain new values

### CODE REVIEW

**Comment by pavelnikolov** [comment]
@araamini the DCO check has failed. Can you, please, resolve that?

**Comment by araamini** [comment]
@pavelnikolov Can you check now?

**Review by pavelnikolov — APPROVED** [review]

**Comment by pavelnikolov** [comment]
Check still fails

**Comment by pavelnikolov** [comment]
@araamini could you, please, GPG sign your commits and bump the chart version?

**Pull request closed without merging**
