### PR TITLE
[jaeger] exposing 16685 for helm and allinone deploy

### PR DESCRIPTION
**Pull request by palmheads**
#### What this PR does

When using the all-in-one jaeger deploy with helm, opens up port 16685 which currently gets a connection refused

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format,
will close that issue when PR gets merged)*

- fixes #3852

#### Checklist

- [ ] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [ ] Chart Version bumped
- [ ] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [ ] README.md has been updated to match version/contain new values

### CODE REVIEW

**Review by mehta-ankit — COMMENTED** [review]
Change LGTM. Svc already had the port defined: https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/allinone-query-svc.yaml#L15

@palmheads can you please bump the version and GPG sign your commit. Thanks!

**Review by mehta-ankit — APPROVED** [review]

**Comment by mehta-ankit** [comment]
@palmheads can you squash your commits into one if possible ? That way you only need to gpg sign 1 commit

**Comment by palmheads** [comment]
Hi @mehta-ankit - haven't done a squash before - was that what you are looking for?

**Comment by mehta-ankit** [comment]
@palmheads You would also need to rebase with main branch as another PR merged and you now have conflicts. Thanks

**Pull request closed without merging**
