### PR TITLE
[jaeger] Update readme to include cookie secret flag and oauth2 doc link

### PR DESCRIPTION
**Pull request by cloudoutloud**
Signed-off-by: cloudoutloud <39462069+cloudoutloud@users.noreply.github.com>

#### What this PR does

Update readme to include cookie secret flag this is mandatory for the proxy config.
Bump image version to latest in YAML example.

#### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format,
will close that issue when PR gets merged)*

- fixes #

#### Checklist

- [x] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [x ] Chart Version bumped
- [x] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [x] README.md has been updated to match version/contain new values

### CODE REVIEW

**Comment by mehta-ankit** [comment]
@cloudoutloud Can you sing off your update chart version commit too
image

As you can see only 1 has that comment. its the `git commit -s` or --signoff options

**Comment by cloudoutloud** [comment]
I have signed off commit, seems I got other changes in this PR now is that normal?

**Comment by mehta-ankit** [comment]
> I have signed off commit, seems I got other changes in this PR now is that normal?

no that's not normal. those changes should not be in this PR. there are few ways u can fix it, one of them is to
1)  Copy your commit sha's and reset hard to origin/main branch and then cherry-pick your two commit's (`git cherry-pick <sha>`)

Another could be plain rebase of you branch with origin/main.

**Comment by cloudoutloud** [comment]
@mehta-ankit 
I did a plain rebase now it just has my changes

**Review by mehta-ankit — APPROVED** [review]

**Pull request merged**
