### PR TITLE
[jaeger] add mehta-ankit as a chart maintainer

### PR DESCRIPTION
**Pull request by naseemkullah**
I'd like to nominate @mehta-ankit as a chart maintainer, he has been making steady contributions for some time.

@mehta-ankit if you are willing to take this up please approve this PR, however if you don't have the time/will it's not a problem we hope you continue to contribute.

@pavelnikolov @mikelorant @dvonthenen Would be nice to get at least one of your approvals.

Ankit will need to be added to the chart maintainers e-mail group.

### CODE REVIEW

**Review by mehta-ankit — APPROVED** [review]

**Comment by mehta-ankit** [comment]
Thanks @naseemkullah .
I would be interested in helping maintain this chart and make it better in the future.

**Comment by yurishkuro** [comment]
@jaegertracing/helm-charts-maintainers please approve if no concerns

**Comment by naseemkullah** [comment]
Bump

**Comment by jpkrohling** [comment]
@naseemkullah , what's the current state around the maintainers of this repository? Have they all been active, or should we consider moving one (or more) of them into emeritus maintainers?

https://github.com/jaegertracing/jaeger/blob/master/GOVERNANCE.md#changes-in-maintainership

**Comment by naseemkullah** [comment]
I think @dvonthenen and @mikelorant could become emeritus maintainers if they agree.

They have been, since I began working on this chart back when it was in https://github.com/helm/charts/tree/master/incubator/jaeger, inactive and almost inactive respectively (@mikelorant did recently chimed in with a comment about a README PR see https://github.com/jaegertracing/helm-charts/pull/166#discussion_r503888515)

We could definitely use some fresh blood!

**Comment by jpkrohling** [comment]
Looks like @mikelorant isn't a maintainer here: 

image

Which maintainers from this list aren't active anymore and could be moved to emeritus, besides @dvonthenen ?

**Comment by naseemkullah** [comment]
That would be it @jpkrohling for the time being!

@pavelnikolov still reviews on a semi-regular basis

We could add @mikelorant to emeritus along with @dvonthenen  as they were both part of original maintainers back in incubator repo https://github.com/helm/charts/commit/42892c2304f89d389ab7cd747d591d876fadb0e5

**Comment by cpanato** [comment]
@jpkrohling You can move me as well, I'm not contributing much these days

**Comment by mikelorant** [comment]
Happy to help out if needed.

**Comment by jpkrohling** [comment]
@naseemkullah, I'm approving and merging this one as is, as I can second @mehta-ankit's nomination based on the previous contributions. Please, to open an issue with the changes necessary regarding the emeritus maintainers.

**Comment by jpkrohling** [comment]
Change of plans: looks like there are now conflicts, so, can't merge this one. But I'm approving this anyway.

**Review by jpkrohling — APPROVED** [review]

**Comment by naseemkullah** [comment]
Thanks @jpkrohling will he be added to the email group as well?

**Comment by pavelnikolov** [comment]
My email has changed, so I'll send a PR with my new email.

**Comment by mehta-ankit** [comment]
> Thanks @jpkrohling will he be added to the email group as well?

@naseemkullah Is there anything else that's needed to let me merge a PR or approve a PR. Coz currently my approval is still gray and not green 😅  (and i don't think i can merge any PR's)

**Comment by yurishkuro** [comment]
@mehta-ankit you were not added to maintainers, I just did it, you should receive an invite.

image

**Comment by mehta-ankit** [comment]
@yurishkuro Thank you. Yes i did receive an invite and accepted it as well. 🙏🏽

**Pull request merged**
