### PR TITLE
[jaeger] Add Toggle switch for AllInOne Ingress

### PR DESCRIPTION
**Pull request by varet80**
Add Ability to controll Ingress in case of use allInOne installation

#### Checklist

- [x] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)

### CODE REVIEW

**Review by naseemkullah — APPROVED** [review]

**Comment by pavelnikolov** [comment]
@billiaz your commits need to be gpg signed

**Comment by GuyCarmy** [comment]
@varet80 any chance you follow the request to gpg sign the commits?

I was about to create the exact same PR, this is really needed.

**Comment by pavelnikolov** [comment]
@GuyCarmy feel free to raise another PR. This seems like an insignificant change and if you can speed up the process I'd be happy to merge it.

**Review by uesleilima — APPROVED** [review]

**Comment by uesleilima** [comment]
Looking forward to this change being merged!

**Comment by o-shevchenko** [comment]
https://github.com/jaegertracing/helm-charts/pull/359 was merged

**Comment by pavelnikolov** [comment]
@varet80 I tried to resolve the conflicts in this PR [with this commit](https://github.com/jaegertracing/helm-charts/pull/331/commits/e7db06241e34ec6c0e6a8ff39d7acb23fee78d87), but now I don't see the changes in the PR.

**Comment by pavelnikolov** [comment]
Ah, it seems that this was already taken care of in #359

**Pull request closed without merging**
