### PR TITLE
Updated charts to use v1.16.0

### PR DESCRIPTION
**Pull request by jpkrohling**
Both Jaeger and Jaeger Operator have been released today under the version 1.16.0. This PR updates the charts to use the new versions.

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
Are there other places needing update? Should the chart version be bumped as well?

**Comment by naseemkullah** [comment]
> Are there other places needing update? Should the chart version be bumped as well?

The tag is also mentioned in both these charts' READMEs

I usually do a search on the tag such as `1.15.1` first to make sure.

As for chart version bumping, yes that looks good.

**Comment by naseemkullah** [comment]
Hi @jpkrohling could you please resolve conflicts and update READMEs with new image tag as well?

**Comment by jpkrohling** [comment]
Done!

**Pull request merged**
